#!/bin/zsh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login &

setxkbmap us &

# exec bspwm &

session=${1:-bspwm}

case $session in
	    dwm           ) exec dwm;;
	    # No known session, try to run it as command
	    *                 ) exec $1;;
esac &

# Temporary Startup Wallpaper while the WM loads
#xwallpaper --zoom ~/Documents/Artix-Wall2.png &

# Pipewire

exec pipewire &
exec wireplumber &
exec pipewire-pulse &

# MPD
killall mpd &
exec mpd --no-daemon
